version: '3.1'

services:

  # ===================================================================================================================

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"

  # ===================================================================================================================